### ISSUE TITLE
Adapt MathML parsing to `lutaml-model` mixed-content changes

### ISSUE THREAD

**Issue by suleman-uzair** [plurimath/plurimath#437]
Several open PRs have failing GHA `rake` test jobs after resolving `lutaml-model 0.8.16`:

- #430
- #434 

The failures appear to come from a compatibility gap in Plurimath's MathML translation path. Newer `lutaml-model` can yield whitespace-only text nodes and singular mapped marker elements through `each_mixed_content`. Plurimath's MathML AST construction currently assumes the older output shape.

Examples seen in CI/local reproduction:

- `spec/plurimath/integration/asciimath_spec.rb:12`
- `spec/plurimath/mathml/v3/section_3_spec.rb:1889`
- `spec/plurimath/mathml_spec.rb:1320`

The Plurimath fix should adapt MathML child handling to the newer `lutaml-model` behavior, especially for whitespace-only children and MathML marker elements such as `<mprescripts/>`.

**Comment by opoudjis** [comment]
Confirming this exact behaviour from a downstream consumer (`metanorma-iso`),
with one notable wrinkle: the failure is **silent** at the consumer call site,
so it surfaces only as an output diff rather than as a raised exception. Writing
this up for the record in case it helps the test surface for PR #438.

## Downstream symptom

`metanorma-iso spec/isodoc/inline_spec.rb:159` ("localises numbers in MathML")
fails because the expected `<asciimath>` sibling element is no longer being
emitted alongside `<math>` in the presentation XML. Expected output contains:

```xml
<fmt-stem type="MathML">
  <semx element="stem" source="_">
    <math xmlns="http://www.w3.org/1998/Math/MathML"> ... </math>
    <asciimath>P (X ge X_(max)) = sum_(j = X_(max))^(1000) ([[0.0001], [j]]) p^(j) (1000.00001 - p)^(1.003 - j)</asciimath>
  </semx>
</fmt-stem>
```

Actual output is missing the `<asciimath>` element entirely.

## Trace

The element is generated by `IsoDoc::PresentationXMLConvert#asciimath_dup`
(`isodoc/lib/isodoc/presentation_function/math.rb:181-190`):

```ruby
def asciimath_dup(node)
  @suppressasciimathdup || node.parent.at(ns("./asciimath")) and return
  math = node.to_xml.gsub(...)
  ret = Plurimath::Math.parse(math, "mathml").to_asciimath
  node.next = "<asciimath>#{@c.encode(ret, :basic)}</asciimath>"
rescue StandardError => e
  warn "Failure to convert MathML to AsciiMath\n#{node.parent.to_xml}\n#{e}"
end
```

The rescue catches the exception from `Plurimath::Math.parse(...).to_asciimath`,
prints a warning to stderr, and proceeds — so the missing `<asciimath>` only
surfaces in test diffs (or as observably-wrong rendered output downstream).

The full exception chain on the metanorma-iso failing spec (Ruby 4.0.5,
`plurimath 0.10.5`, `mml 2.3.7`, `lutaml-model 0.8.16`):

```
NoMethodError: undefined method 'to_asciimath' for nil
  plurimath/math/function/tr.rb:18  Tr#to_asciimath block
  plurimath/math/function/tr.rb:17  Array#map
  plurimath/math/function/table.rb:45  Table#to_asciimath block
  plurimath/math/function/fenced.rb:30  Fenced#to_asciimath block
  plurimath/math/formula.rb:62  Formula#to_asciimath block
  -> wrap_render_error rescues StandardError
  -> raises ParseError.new(input_string, :asciimath)
```

Hence the confusing user-facing error message wording ("Failed to parse the
following formula with type `asciimath`") even though the formula in the
"FORMULA BEGIN/END" block is in fact the original MathML and was passed with
type `"mathml"`.

## Root cause confirmed for lutaml-model mixed-content

Bisected to the adapter switch. `relaton-bib 2.1.4`'s
`lib/relaton/bib/model/item.rb:42` does this at gem-load time:

```ruby
Lutaml::Model::Config.configure do |config|
  config.xml_adapter_type = :nokogiri
end
```

So merely `require "isodoc"` (which transitively loads `relaton-bib`) globally
switches the lutaml-model XML adapter from Ox to Nokogiri for the rest of the
process — including `Mml.parse` calls made later by
`Plurimath::Mathml::Parser`.

Under the Nokogiri adapter, `Mml::V4::Munderover#each_mixed_content` yields
text-node children:

```
"\n            "        # whitespace string
Mml::V4::Mrow          # base
"\n            "        # whitespace string
Mml::V4::Mrow          # underscript
"\n            "        # whitespace string
Mml::V4::Mrow          # overscript
"\n          "          # trailing whitespace string
```

`FormulaTransformation#ordered_children` returns them all; `content_children`
filters only `Malignmark`/`Maligngroup`; `munderover_to_underover` then takes
`children[0]`, `children[1]`, `children[2]` as base/under/over — which are now
two whitespace strings and one `Mrow`. `base` and `overscript` end up `nil`.

Same cascade in `msub`, `msup`, `munder`, `msubsup`, and any other site that
indexes into `content_children(node)` by position.

Under the Ox adapter, `each_mixed_content` returns only the three `Mrow`
elements, no whitespace strings — which is why the same MathML round-trips
cleanly there.

## Local fix confirmed equivalent to #438

I verified PR #438's `ordered_children` change resolves the metanorma-iso
spec. Patching the installed gem with just:

```ruby
def ordered_children(node)
  children = []
  node.each_mixed_content do |child|
    next if child.is_a?(String) && child.strip.empty?
    children << child
  end
  children
end
```

turns `inline_spec.rb` from 8/9 → 9/9 green, including `:159`. PR #438 goes
further (handles `<mprescripts>` markers via `Mml::Base::*`, adds round-trip
test coverage across Ox/Oga/Nokogiri), and that broader scope is the right
call — `msup`/`msub`/`msubsup` are equally affected.

## Suggestion: add the metanorma-iso failure to the test surface

The reason this slipped past plurimath's own CI but landed in metanorma-iso
output is exactly the silent-rescue at `asciimath_dup`. If
`Plurimath::Mathml::FormulaTransformation` had a test that exercises pretty-
printed MathML containing `<munderover>` (or `<msup>` with nested operands)
under each adapter explicitly, this regression would have been caught
upstream before reaching the metanorma stack. PR #438's new round-trip suite
across adapters covers this — recommend keeping that broad coverage.

🤖
